version: 2.1

orbs:
  python: cjw296/python-ci@4

jobs:
  machine-run-tests:
    parameters:
      prepare:
        type: steps
        default: []
      python:
        type: string
        default: python3
      command:
        type: string
    machine:
      image: ubuntu-2204:2023.02.1
    steps:
      - steps: << parameters.prepare >>
      - python/pip-run-tests:
          python: << parameters.python >>
          command: << parameters.command >>

common: &common
  jobs:
    - machine-run-tests:
        name: docker
        prepare:
          - run: "docker info"
        command: pytest --cov -m "not no_containers"
    - machine-run-tests:
        name: podman
        prepare:
          - run: "sudo apt-get remove docker-ce"
          - run: "sudo apt-get update"
          - run: "sudo apt-get install podman"
          - run: "systemctl --user start podman.socket"
          - run: "podman info"
        python: DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock python3
        command: pytest --cov  -m "not no_containers"
    - machine-run-tests:
        name: nothing
        prepare:
          - run: "sudo apt-get remove docker-ce"
        command: pytest --cov -m "not containers"
    - python/pip-run-tests:
        command: pytest --cov -m "not containers"
        matrix:
          parameters:
            image:
              - cimg/python:3.11
              - cimg/python:3.12

    - python/coverage:
        name: coverage
        requires:
          - python/pip-run-tests
          - docker
          - podman
          - nothing

    - python/typing:
        packages: testservices tests
        image: cimg/python:3.12

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
